### ISSUE TITLE
Status: Unknown

### ISSUE THREAD

**Issue by olemr** [Pavion/org.openhab.binding.twinklytree#1]
Hello.
Took your binding for a spin, but Status is stuck on Unknown.
Downloaded and installed from the marked place (also tried the .jar, same issue)
Tried to enable more logging in karaf, but nothing shows.
![image](https://user-images.githubusercontent.com/28068256/147165518-60eb9f43-a491-499c-a7a2-3c9972174c54.png)
When restarting openHab, no errors in the log.
When restarting the bundle in karaf, the text HANDLER_MISSING_ERROR is briefly shown under the Status in the browser:
(not able to snip it)
![image](https://user-images.githubusercontent.com/28068256/147165656-b311a5cb-de54-49d9-835f-02abae0aa333.png)
My Twinkly received a new FW update today. I'm now on 2.8.3 on a II gen. 250 RGBW chain.
Mobile app works fine.
My python script restAPI from yesteryear works fine on the new FW.
I added the thing from the GUI. Have no .things file.
![image](https://user-images.githubusercontent.com/28068256/147165904-98345341-df14-4e0f-a454-ff63ed00e08d.png)
My openHab version is
![image](https://user-images.githubusercontent.com/28068256/147166164-fdaf36be-4909-4af6-a7b7-236696159835.png)

**Comment by Pavion** [comment]
Hello! 
Are you sure the binding is not working? :) 
If you don't specify a refresh time, the binding don't query the channel state and stay UNKNOWN until the first command. 
If the refresh is specified, binding should go online and you would see more debug in your log:
```
log:set DEBUG org.openhab.binding.twinklytree
```
BR Pav

**Comment by olemr** [comment]
Ah, I set refresh to 10 and linked the On/Off channel and then it came Online. :-)
Just a different behavior from all other bindings I have used.
Thanks for this! I can now retire my executeCommandLine("/usr/bin/python3" ...
